# Generated by Django 3.2.9 on 2021-11-21 21:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_alter_usertimer_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertimer',
            unique_together={('user', 'timers')},
        ),
    ]
