# Generated by Django 3.2.9 on 2021-11-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usertimer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimer',
            name='display_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
