# Generated by Django 3.2.9 on 2021-11-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usertimer_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimer',
            name='display_order',
            field=models.IntegerField(db_column='display_order'),
        ),
    ]
