# Generated by Django 3.2.9 on 2021-12-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usertimer_display_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
