# Generated by Django 3.2.9 on 2021-11-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=200)),
                ('route_id', models.CharField(max_length=200)),
                ('direction_id', models.CharField(max_length=200)),
                ('timer_id', models.CharField(max_length=200)),
                ('predictions_url', models.CharField(max_length=5000)),
                ('schedule_url', models.CharField(max_length=5000)),
                ('stop_name', models.CharField(max_length=200)),
                ('route_name', models.CharField(max_length=200)),
                ('direction_name', models.CharField(max_length=200)),
            ],
        ),
    ]
